### ISSUE TITLE
Error 400!

### ISSUE THREAD

**Issue by blurunnner** [mike-levenick/mut#15]
Hi, what does it mean when I get "Failed! - 400!" as an error code?

**Comment by mike-levenick** [comment]
Hello. It depends on the situation. My recommendation is to turn on "advanced debugging" from the settings menu at the top, and see what the specific error that it reports is. 

If you would like, you can turn on advanced debugging, and then save the whole log file and post it here and I'd be happy to take a look.

![screen shot 2018-08-09 at 12 00 15 pm](https://user-images.githubusercontent.com/12515543/43913864-dcc13eae-9bcb-11e8-8a54-0c27edcc1326.png)
![screen shot 2018-08-09 at 12 00 24 pm](https://user-images.githubusercontent.com/12515543/43913869-de5c47fe-9bcb-11e8-83e7-e366a9cee8a9.png)

**Comment by blurunnner** [comment]
Hi Mike, thanks. Attached is the file.
[MUT-Output-2018-08-09_16.03.log](https://github.com/mike-levenick/mut/files/2275770/MUT-Output-2018-08-09_16.03.log)

My thought: Most of these devices are added to JAMF in pre-enrollment, but they haven't actually been turned on to have the profile installed. Do you think that is it?

**Comment by mike-levenick** [comment]
Ahh, yes. You got it. 

MUT updates Mobile Device Names a bit differently than it updates any other field. In order to enforce the name change so that it sticks, MUT will actually generate an MDM command on the device to update the name.

This MDM command requires that device name changes are not blocked (restriction payload on a configuration profile), and they also will not actually take effect until the device processes the MDM command.

If another name change is submitted via MUT before the first name change command actually processes, you will receive a 400 error, and it will state that the command is already pending under Advanced Debugging. You can see this pending command on the management section of the device record.

To get the name changes to actually take effect, the device has to be turned on, on network, MDM capable, talking to Jamf Pro, and all that jazz—as soon as it processes the MDM command that's pending, the name will update.

**Comment by blurunnner** [comment]
Thanks, I'll try it again once they're all up and running!
