### ISSUE TITLE
User record update- Failing

### ISSUE THREAD

**Issue by snourse** [mike-levenick/mut#17]
I'm uploading a file that contains usernames and the group they need to go in.  I get an error that indicates The Mut is searching for a device rather than user.. 

Device 901053957 - Failed! - 404!

HTTP 404 means 'not found'. There is no device with id 901053957 enrolled in Jamf Pro.

Full Response Data:
<html>
<head>
   <title>Status page</title>
</head>
<body style="font-family: sans-serif;">
<p style="font-size: 1.2em;font-weight: bold;margin: 1em 0px;">Not Found</p>
<p>The server has not found anything matching the request URI</p>
<p>You can get technical details <a href="http://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html#sec10.4.5">here</a>.<br>
Please continue your visit at our <a href="/">home page</a>.
</p>
</body>
</html>

**Comment by mike-levenick** [comment]
Yes, sorry, this error is totally wrong. It's on my list to fix for the next version.

What this 404 is indicating when updating groups is actually that the GROUP does not exist. It's not actually looking for the device or user, because it's adding the object to the /usergroups endpoint. 

Thank you for bringing it to my attention. It is definitely on the list of things to be fixe din the next release.

**Comment by mike-levenick** [comment]
Fixed in v5.
