### ISSUE TITLE
Feature Request - Update Multiple Columns

### ISSUE THREAD

**Issue by allkindsofralph** [mike-levenick/mut#18]
Any plans on updating multiple columns? I currently have a Numbers Spreadsheet that has all the information I want for multiple columns, but use separate sheets to pull the certain column for the needed export. I then export and have all the CSVs I need to update but it would be awesome if we could submit one CSV with all the columns I want updated.

Thanks so much for this app! It is seriously amazing!

**Comment by mike-levenick** [comment]
Thanks for the comment. So, updating multiple columns is by far the most popular feature request for MUT. It's something that I think would be neat to do, but I'm not sure who to implement it well, and in a safe way. 

See: 
https://www.jamf.com/jamf-nation/discussions/25744/mut-v4-ux-features-discussion
and
https://www.jamf.com/jamf-nation/discussions/24572/multiple-columns-in-a-mut-csv

For now, I think I'll hold off on this, since Inventory Preload is now a thing. 
https://docs.jamf.com/10.8.0/jamf-pro/administrator-guide/Inventory_Preload.html

It operates similarly (although different) from MUT, but does allow updates to multiple fields at once. 

Hope this helps!

**Comment by mike-levenick** [comment]
@allkindsofralph you'll be happy to know that @benwhitis and I are hard at work on v5 which will have multiple attribute updates possible.

You can check out a preview here: https://www.youtube.com/watch?v=igaa5Zur3jU

We're working on getting the UI fixed up to accommodate  the new features, but the backend is just about done, and we're hoping to be able to release at some point in the next month or two.

**Comment by allkindsofralph** [comment]
Woohoo! you guys are awesome!
