### ISSUE TITLE
JSS 409! Error Code

### ISSUE THREAD

**Issue by gernb014** [mike-levenick/mut#3]
I keep getting the 409! error when I try to run a building update from serial numbers. The weird thing is that it works when the CSV is only 1 row but when I add anything below no dice. Another kind of weird thing I notice is that when I have multiple rows it still says "Found 1 rows in the CSV". Most likely it is a user error. Anything in the right direction would be awesome. Things I know: the building already exists, the serial numbers are in the JSS since the same one went through when I do it one by one. 
<img width="490" alt="screen shot 2017-07-24 at 1 56 58 pm" src="https://user-images.githubusercontent.com/30417742/28539780-83a712fa-7078-11e7-90a0-56506c187e17.png">
<img width="485" alt="screen shot 2017-07-24 at 1 57 28 pm" src="https://user-images.githubusercontent.com/30417742/28539784-882afb2a-7078-11e7-8b05-73b7f1a1481e.png">

**Comment by mike-levenick** [comment]
Hello. Assuming you're using excel for making the CSV, try doing an export as "Windows Comma Separated (CSV)". 

You can run a cat on the file in terminal with the command:
`cat /Users/jgernbacher/Desktop/Test 1.csv` 
which will tell you how the computer actually sees the contents of that file--I'm guessing it's a bit goofy. We see that sometimes with files exported from Excel. Seems to be hit or miss.

Otherwise, do any of your other building titles have commas in them? That will make MUT freak out.

**Comment by gernb014** [comment]
Closed in 9 minutes! That was the trick! Thanks Mike for jumping on this so quick! Your product is amazing.

**Comment by mike-levenick** [comment]
I'm assuming it was the Windows Comma Separated that did it? 

Glad to hear it!

**Comment by gernb014** [comment]
Yes. Just dropped it down to the WCS instead of CSV. Thank you!

**Comment by mike-levenick** [comment]
Excellent, glad to hear it. Have a great day!
