### ISSUE TITLE
Issues handling Spanish n "ñ"

### ISSUE THREAD

**Issue by damacguy** [mike-levenick/mut#33]
We have an EA where one of the options is "Español". But we can't import with the ñ character. The character is read as a line break or something. So the EA shows "Espa" and the serial number on the next line is shown as "ol"! You can see in this screenshot. [Screen Shot 2019-07-31 at 3 29 40 PM](https://user-images.githubusercontent.com/7740383/62241959-35342c00-b3a8-11e9-8b7c-53b0ee76b2e8.png)

**Comment by mike-levenick** [comment]
Interesting. I just tested in MUT Classic (4.3) and it does NOT do the same behavior. It seems to parse "Español" properly.

We are using a new CSV parser in MUT v5, and I'm wondering if that's part of the reason..

For what it's worth, in the mean time, you can still get MUT Classic from the app store, which is basically rebranded MUT v4.3. Use that to update your extension attribute with the ñ for now, and we'll look into parsing these characters in V5.

**Comment by mike-levenick** [comment]
Wow, yeah. I just threw an ñ into an asset tag and fed it to V5, and it _really_ does not like that... it caused the whole array to not parse properly, and threw an index out of bounce error and crashed the app. 

We'll work on this ASAP.

**Comment by mike-levenick** [comment]
Another update. From what I can tell, this seems to be an issue with how Excel is saving the file with an ñ in it. I thought that 4.3/classic was handling it better because I had created that CSV in VIM.

When I create the file in VIM, then MUT handles it properly. But when I create it in excel, it does not. 

![Screen Shot 2019-07-31 at 3 01 03 PM](https://user-images.githubusercontent.com/12515543/62244175-7fb3a980-b3a4-11e9-9602-da2306bb3f36.png)

![Screen Shot 2019-07-31 at 3 04 39 PM](https://user-images.githubusercontent.com/12515543/62244185-893d1180-b3a4-11e9-8489-51d2209b6964.png)

For what it's worth, it looks like Google Sheets will handle this properly. @damacguy Go ahead and re-build your sheet in Google Sheets and export as CSV and see how that works for you.

![Screen Shot 2019-07-31 at 3 07 37 PM](https://user-images.githubusercontent.com/12515543/62244391-f51f7a00-b3a4-11e9-93de-5d957f9b28f4.png)

![Screen Shot 2019-07-31 at 3 06 49 PM](https://user-images.githubusercontent.com/12515543/62244397-f81a6a80-b3a4-11e9-8acc-7de6ce0eb897.png)

**Comment by mike-levenick** [comment]
Final update--it seems that Excel can and will work, if you do File > Save As > CSV UTF-8.

![Screen Shot 2019-07-31 at 3 10 48 PM](https://user-images.githubusercontent.com/12515543/62244608-65c69680-b3a5-11e9-9de8-667e1617677b.png) 


![Screen Shot 2019-07-31 at 3 10 00 PM](https://user-images.githubusercontent.com/12515543/62244589-5ba49800-b3a5-11e9-8a82-de4195fec41d.png)

**Comment by mike-levenick** [comment]
Chatted on slack--issue resolved with saving as CSV UTF-8.
