### ISSUE TITLE
Program Crashes Immediately

### ISSUE THREAD

**Issue by yhttech** [mike-levenick/mut#46]
JAMF Support told me to download the tool to make bulk group edits.  I've downloaded it 3 times, and each time I try to log in, it crashes immediately after I enter my password.

**Comment by mike-levenick** [comment]
I had another report of this recently--are you putting the /index.html in your URL when you log in?

Your login URL should just be https://instancename.jamfcloud.com

Alternatively, if you're using Jamfcloud, you can even just use 'instancename'. For example, my login looks something like this:

![image](https://user-images.githubusercontent.com/12515543/91094083-ecd55500-e61f-11ea-936b-f9450dfe02c6.png)

**Comment by yhttech** [comment]
Yes, I was.  Thank you.
If I'm adding iPads to static groups, can I add a column called "group
name" to the CSV or is there another method?

Mr. David Horowitz
IT Director
Yeshiva Har Torah
250-10 Grand Central Parkway
Little Neck, NY 11426

(718) 343-2533

**Comment by mike-levenick** [comment]
https://github.com/mike-levenick/mut#static-group-updates

This should walk you through it! You'll need just a spreadsheet of all the devices to add to a single group, and then it'll do bulk updates to that one group (one group per upload).

If you have many devices to add to many groups, the method that MUT Classic (available on the app store) uses will have a column A and a column B and you can drop various devices into various groups in one run--but it goes much slower as it does one line at a time instead of the whole bulk update.

Hope this helps!
