### ISSUE TITLE
Adding records

### ISSUE THREAD

**Issue by sifivemike** [mike-levenick/mut#62]
Hope this is an appropriate place to ask this question. I am interested in adding new Users in bulk to Jamf from a CSV. Am I right in concluding (after reading the docs and looking at the video) that this is NOT possible with the MUT, that the MUT can only be used to update existing user records?
We run Okta here, not any kind of LDAP server, so are at a loss as to how we can get our users into Jamf so they can get matched up to the many devices already enrolled. 

Mike

**Comment by mike-levenick** [comment]
Hey Mike,

good place to ask and good question. 

The short answer is “yes with an asterisk”. 

Basically, MUT cannot create users, but Jamf Pro will create users on-demand if they’re assigned to a device, and that user does not yet exist. 

So pick a device, like a test device, and just assign all your users to that device one-by-one. 

As each user is assigned to the device, Jamf Pro will create them if they currently do not exist. 

The caveat here is that any other user information (such as “full name”) on that device will be auto populated to the new user. So either make sure the device has no user info when you start, or make sure all the user columns are populated correctly in your CSV, otherwise you end up with a bunch of users with the same full name/phone number etc. 

Sorry if this is confusing… feel free to email if you need more clear instruction.

**Comment by sifivemike** [comment]
Thanks Mike for the quick reply. I think I understand all you wrote. I'll give it a try, and post again if I have issues. 
Thanks for writing the MUT!

**Comment by sifivemike** [comment]
Working as expected, great!

One side note that might be helpful to others:
I was wondering why the user template seemed to have fewer user-related fields than the computer template, which includes Department, Building, Room. But then I realized Jamf considers those attributes of the computer, not the user.
